# Generated by Django 2.0.2 on 2018-03-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ClientUser', verbose_name='плательщик'),
        ),
    ]
