# Generated by Django 2.0.2 on 2018-03-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20180305_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gateway_response',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='данные ответа платежного шлюза'),
            preserve_default=False,
        ),
    ]
