# Generated by Django 2.0.2 on 2018-03-05 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20180305_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gateway_status',
            field=models.CharField(blank=True, max_length=1024, verbose_name='данные статуса платежного шлюза'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_sber',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Заказ зарегистрирован, но не оплачен'), (1, 'Предавторизованная сумма захолдирована (для двухстадийных платежей)'), (2, 'Проведена полная авторизация суммы заказа'), (3, 'Авторизация отменена'), (4, 'По транзакции была проведена операция возврата'), (5, 'Инициирована авторизация через ACS банка-эмитента'), (6, 'Авторизация отклонена')], default=0, verbose_name='Статус платежной системы'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp_billing',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='время проведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp_sber',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='время оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Новая'), (1, 'Создана'), (2, 'Успешна'), (3, 'Возвращена')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
    ]
