# Generated by Django 2.0.2 on 2018-03-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20180305_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.ClientUser', verbose_name='плательщик'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Новая'), (1, 'Создана'), (2, 'Успешна'), (3, 'Ошибка/Возврат')], default=0),
        ),
    ]
