# Generated by Django 2.0.2 on 2018-03-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20180306_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service_id',
            field=models.PositiveIntegerField(blank=True, verbose_name='ID услуги'),
        ),
    ]
