# Generated by Django 2.0.2 on 2018-03-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20180313_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Сумма (коп.)'),
        ),
    ]
