# Generated by Django 2.0.2 on 2018-03-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20180313_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ClientUser', verbose_name='Плательщик'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='final_url',
            field=models.URLField(verbose_name='URL для редиректа после потверждения оплаты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway_response',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Данные ответа платежного шлюза'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway_status',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Данные статуса платежного шлюза'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paysys_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер заказа в платежной системе'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status_sber',
            field=models.PositiveSmallIntegerField(choices=[(-1, '-----'), (0, 'Заказ зарегистрирован, но не оплачен'), (1, 'Предавторизованная сумма захолдирована (для двухстадийных платежей)'), (2, 'Проведена полная авторизация суммы заказа'), (3, 'Авторизация отменена'), (4, 'По транзакции была проведена операция возврата'), (5, 'Инициирована авторизация через ACS банка-эмитента'), (6, 'Авторизация отклонена')], default=-1, verbose_name='Статус платежной системы'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp_billing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp_sber',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
