# Generated by Django 2.0.2 on 2018-03-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20180313_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sber_client_cardholder_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя держателя карты'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sber_client_ip',
            field=models.CharField(blank=True, max_length=30, verbose_name='IP адрес покупателя'),
        ),
    ]
