# Generated by Django 2.0.2 on 2018-03-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20180307_0644'),
        ('transactions', '0013_auto_20180313_1611'),
    ]

    operations = [
    ]
