# Generated by Django 2.0.2 on 2018-03-14 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_merge_20180314_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ClientUser', verbose_name='Плательщик'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Новая'), (1, 'Создана'), (2, 'Успешна'), (3, 'Ошибка/Возврат')], default=0, verbose_name='Статус'),
        ),
    ]
