# Generated by Django 2.0.2 on 2018-03-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20180314_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='task_id (20 мин.)'),
        ),
    ]
