# Generated by Django 2.0.2 on 2018-03-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0017_transaction_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Новая'), (1, 'Создана'), (2, 'Успешна'), (3, 'Ошибка/Возврат'),
                         (4, 'Передача информации биллингу'), (5, 'Успешна (инф. передана биллингу)')], default=0,
                verbose_name='Статус'),
        ),
    ]
