# Generated by Django 2.0.2 on 2018-03-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_userid', models.IntegerField(verbose_name='идентификатор пользователя в системе биллинга')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Billing', verbose_name='биллинг')),
            ],
            options={
                'verbose_name': 'плательщик',
                'verbose_name_plural': 'плательщики',
            },
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('role', models.CharField(choices=[('AC', 'Бухгалтер'), ('AD', 'Админ')], max_length=2, verbose_name='роль пользователя')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.AlterUniqueTogether(
            name='clientuser',
            unique_together={('billing', 'billing_userid')},
        ),
    ]
