# Generated by Django 2.0.2 on 2018-03-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_staffuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('AC', 'Бухгалтер'), ('AD', 'Админ')], max_length=2, verbose_name='Роль пользователя'),
        ),
    ]
