# Generated by Django 2.0.2 on 2018-03-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180313_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='role',
        ),
    ]
