# Generated by Django 2.0.2 on 2018-03-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name': 'Биллинг', 'verbose_name_plural': 'Биллинги'},
        ),
        migrations.AlterModelOptions(
            name='counteragent',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterField(
            model_name='billing',
            name='counter_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.CounterAgent', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
