# Generated by Django 2.0.2 on 2018-03-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180305_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='url',
            field=models.URLField(verbose_name='URL биллинга'),
        ),
    ]
