# Generated by Django 2.0.2 on 2018-03-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20180313_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteragent',
            name='commission',
            field=models.PositiveSmallIntegerField(default=0, help_text='проценты (0 - 100%)', verbose_name='Комиссия (%)'),
        ),
    ]
