# Generated by Django 2.0.2 on 2018-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_counteragent_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='system_name',
            field=models.SlugField(default='', max_length=250, unique=True, verbose_name='Системное название'),
            preserve_default=False,
        ),
    ]
